FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY core_api.py .
COPY openflow_actuator.py .

EXPOSE 8000

CMD ["uvicorn", "core_api:app", "--host", "0.0.0.0", "--port", "8000"]
